### PR TITLE
Feat:adds Difficulty test

### PR DESCRIPTION
**Pull request by nilejack**
1. Made a test for the difficulty enum.val switch case method.
2. Ran the test successfully and I'm now submitting PR in hopes to land this feature, thanks.

### CODE REVIEW

**Review by htanweer244 — CHANGES_REQUESTED** [review]
Cannot commit commented out code! Please modify - Thank you!

**Comment by nilejack** [comment]
> Cannot commit commented out code! Please modify - Thank you!

Hey Hummad, thanks for catching that. I've made the necessary  changes and updated them in my latest commit.

**Comment by htanweer244** [comment]
Thank you Nile for changes - LGTM!

**Review by jjcapparell — APPROVED** [review]
LGTM

**Review by htanweer244 — APPROVED** [review]

**Review by jjcapparell — CHANGES_REQUESTED** [review]
Test not working might need to move to a model folder

**Pull request closed without merging**
